---
version: '3'
services:
  memcached-server:
    image: memcached:1.6.23-alpine3.19
    networks:
      - reverse-http-net
    ports:
      - 11211:11211
    restart: unless-stopped
  proxy-lb:
    image: nginx:1.25-alpine
    volumes:
      - ./tests/ha/nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    networks:
      - reverse-http-net
  proxy-1:
    hostname: proxy-1
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - proxy
      - '--agent-server.listen-address=:4242'
      - '--agent-server.tls.file.key=/certs/proxy-key.pem'
      - '--agent-server.tls.file.cert=/certs/proxy.pem'
      - '--agent-server.tls.refresh=1s'
      - '--http-proxy.listen-address=:3128'
      - '--auth.type=noauth'
      - '--store.type=memcached'
      - '--store.http-proxy-address=proxy-1:3128'
      - '--store.memcached.address=memcached-server:11211'
    volumes:
      - ./tests/cfssl/certs:/certs:ro
    networks:
      - reverse-http-net
  proxy-2:
    hostname: proxy-2
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - proxy
      - '--agent-server.listen-address=:4242'
      - '--agent-server.tls.file.key=/certs/proxy-key.pem'
      - '--agent-server.tls.file.cert=/certs/proxy.pem'
      - '--agent-server.tls.refresh=1s'
      - '--http-proxy.listen-address=:3128'
      - '--auth.type=noauth'
      - '--store.type=memcached'
      - '--store.http-proxy-address=proxy-2:3128'
      - '--store.memcached.address=memcached-server:11211'
    volumes:
      - ./tests/cfssl/certs:/certs:ro
    networks:
      - reverse-http-net
  agent-4711:
    hostname: agent-4711
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - agent
      - '--agent-client.server-address=proxy-lb:4242'
      - '--agent-client.tls.file.root-ca=/certs/ca.pem'
      - '--auth.noauth.agent-id=4711'
    volumes:
      - ./tests/cfssl/certs:/certs:ro
    networks:
      - reverse-http-net
  agent-4712:
    hostname: agent-4712
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - agent
      - '--agent-client.server-address=proxy-lb:4242'
      - '--agent-client.tls.file.root-ca=/certs/ca.pem'
      - '--auth.noauth.agent-id=4712'
    volumes:
      - ./tests/cfssl/certs:/certs:ro
    networks:
      - reverse-http-net
  lb-1:
    hostname: lb-1
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - lb
      - '--http-proxy.listen-address=:3128'
      - '--auth.type=noauth'
      - '--store.type=memcached'
      - '--store.memcached.address=memcached-server:11211'
    networks:
      - reverse-http-net
  lb-2:
    hostname: lb-2
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - lb
      - '--http-proxy.listen-address=:3128'
      - '--auth.type=noauth'
      - '--store.type=memcached'
      - '--store.memcached.address=memcached-server:11211'
    networks:
      - reverse-http-net
  http-proxy:
    image: nginx:1.25-alpine
    volumes:
      - ./tests/ha/nginx-client.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3128:3128/tcp"
    networks:
      - reverse-http-net

networks:
  reverse-http-net:
