---
version: '3'
services:
  proxy:
    hostname: proxy
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - proxy
      - '--agent-server.listen-address=:4242'
      - '--agent-server.tls.file.key=/certs/proxy-key.pem'
      - '--agent-server.tls.file.cert=/certs/proxy.pem'
      - '--http-proxy.listen-address=:3128'
      - '--auth.type=jwt'
      - '--auth.jwt.public-key=/jwt/auth-key-public.pem'
    volumes:
      - ./tests/cfssl/certs:/certs:ro
      - ./tests/jwt:/jwt:ro
    ports:
      - "3128:3128/tcp"
  agent-4711:
    hostname: agent-4711
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - agent
      - '--agent-client.server-address=proxy:4242'
      - '--agent-client.tls.file.root-ca=/certs/ca.pem'
      - '--auth.type=jwt'
      - '--auth.jwt.token=file:/jwt/auth-agent-jwt-4711.b64'
    volumes:
      - ./tests/cfssl/certs:/certs:ro
      - ./tests/jwt:/jwt:ro
  agent-4712:
    hostname: agent-4712
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - agent
      - '--agent-client.server-address=proxy:4242'
      - '--agent-client.tls.file.root-ca=/certs/ca.pem'
      - '--auth.type=jwt'
      - '--auth.jwt.token=file:/jwt/auth-agent-jwt-4712.b64'
    volumes:
      - ./tests/cfssl/certs:/certs:ro
      - ./tests/jwt:/jwt:ro
